# Generated by Django 5.2.12 on 2026-03-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('direction', models.CharField(choices=[('odoo_to_toc', 'Odoo → TOConline'), ('toc_to_odoo', 'TOConline → Odoo')], default='odoo_to_toc', max_length=20)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('skipped', 'Skipped'), ('partial', 'Partial')], max_length=20)),
                ('odoo_id', models.BigIntegerField(blank=True, null=True)),
                ('toconline_id', models.CharField(blank=True, max_length=255)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duração em milissegundos', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='state.company')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'entity_type', 'status'], name='audit_syncl_company_35a778_idx'), models.Index(fields=['created_at'], name='audit_syncl_created_005a8e_idx')],
            },
        ),
    ]
