# Generated by Django 5.2.12 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("state", "0005_hardening_state_models"),
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alert_type", models.CharField(choices=[("failure_rate", "Failure Rate"), ("token_expired", "Token Expired")], max_length=30)),
                ("message", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sync_alerts", to="state.company"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["alert_type", "created_at"], name="audit_syncal_alert_t_21ac2d_idx"),
                    models.Index(fields=["company", "created_at"], name="audit_syncal_company_8bcab1_idx"),
                ],
            },
        ),
    ]
