# Generated by Django 5.2.12 on 2026-04-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_syncalert"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="syncalert",
            new_name="audit_synca_alert_t_6b3e70_idx",
            old_name="audit_syncal_alert_t_21ac2d_idx",
        ),
        migrations.RenameIndex(
            model_name="syncalert",
            new_name="audit_synca_company_c3d697_idx",
            old_name="audit_syncal_company_8bcab1_idx",
        ),
    ]
