# Generated by Django 5.2.12 on 2026-03-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('odoo', 'Odoo'), ('toconline', 'TOConline')], max_length=20)),
                ('base_url', models.URLField()),
                ('credentials', models.JSONField(default=dict, help_text='JSON com credenciais: {db, username, password} para Odoo ou {client_id, client_secret, refresh_token} para TOConline')),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='state.company')),
            ],
            options={
                'verbose_name': 'Company Connection',
                'verbose_name_plural': 'Company Connections',
                'unique_together': {('company', 'system')},
            },
        ),
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('product', 'Product'), ('tax', 'Tax'), ('invoice', 'Invoice')], max_length=50)),
                ('odoo_id', models.BigIntegerField()),
                ('toconline_id', models.CharField(max_length=255)),
                ('canonical_hash', models.CharField(blank=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='state.company')),
            ],
            options={
                'verbose_name': 'Entity Link',
                'verbose_name_plural': 'Entity Links',
                'indexes': [models.Index(fields=['company', 'entity_type', 'toconline_id'], name='state_entit_company_02b8bd_idx')],
                'unique_together': {('company', 'entity_type', 'odoo_id')},
            },
        ),
    ]
