# Generated by Django 5.2.12 on 2026-03-25 15:57

import state.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_deletiontombstone_entitysnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconnection',
            name='credentials',
            field=state.fields.EncryptedJSONField(default=dict, help_text='JSON com credenciais: {db, username, password} para Odoo ou {client_id, client_secret, refresh_token} para TOConline (encriptado)'),
        ),
        migrations.AlterField(
            model_name='deletiontombstone',
            name='system',
            field=models.CharField(choices=[('odoo', 'Odoo'), ('toconline', 'Toconline')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entitysnapshot',
            name='system',
            field=models.CharField(choices=[('odoo', 'Odoo'), ('toconline', 'Toconline')], max_length=20),
        ),
    ]
