# Generated by Django 5.2.12 on 2026-03-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_add_encrypted_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconnection',
            name='credentials',
            field=models.JSONField(default=dict, help_text='JSON com credenciais: {db, username, password} para Odoo ou {client_id, client_secret, refresh_token, access_token} para TOConline'),
        ),
    ]
