# Generated by Django 5.2.12 on 2026-04-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("state", "0004_revert_to_jsonfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyconnection",
            name="rotated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DeadLetterEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entity_type", models.CharField(max_length=50)),
                ("operation", models.CharField(max_length=100)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField()),
                ("stack_trace", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("is_reprocessed", models.BooleanField(default=False)),
                ("reprocessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dead_letters", to="state.company"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "entity_type", "created_at"], name="state_deadle_company_3df5ea_idx"),
                    models.Index(fields=["is_reprocessed", "created_at"], name="state_deadle_is_repr_46069d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=64, unique=True)),
                ("entity_type", models.CharField(max_length=50)),
                ("operation", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "In Progress"), ("completed", "Completed"), ("failed", "Failed")],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="idempotency_keys", to="state.company"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["company", "entity_type", "operation"], name="state_idempo_company_9f799e_idx"),
                    models.Index(fields=["status", "updated_at"], name="state_idempo_status_4ee30e_idx"),
                ],
            },
        ),
    ]
