# Generated by Django 5.2.12 on 2026-04-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("state", "0005_hardening_state_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="deadletterentry",
            new_name="state_deadl_company_c9aa6f_idx",
            old_name="state_deadle_company_3df5ea_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterentry",
            new_name="state_deadl_is_repr_83e27f_idx",
            old_name="state_deadle_is_repr_46069d_idx",
        ),
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="state_idemp_company_26a477_idx",
            old_name="state_idempo_company_9f799e_idx",
        ),
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="state_idemp_status_55f024_idx",
            old_name="state_idempo_status_4ee30e_idx",
        ),
    ]
